name: signalr_pure
description: SignalR Pure is a library which contains some useful tools for Signalr. It's SignalR Client.
version: 1.0.0+3
homepage: https://github.com/Dimolll/signalr_pure
publish_to: https://pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  meta: ^1.7.0
  tuple: ^2.0.0

dev_dependencies:
  mockito: ^5.0.16
  lints: ^1.0.0
  test: ^1.16.0
